language: ruby
rvm:
  - 2.1.2

before_script:
  - git clone https://gist.github.com/0c4ad3b5700c6364abf1.git -b v1.0 kalibro_install
  - pushd kalibro_install
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - bash install.sh
  - popd
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  # Gatekeeper
  - git clone https://github.com/mezuro/kalibro_gatekeeper.git -b v0.1.0 kalibro_gatekeeper
  - cd kalibro_gatekeeper
  - cp config/database.yml.sample config/database.yml
  - cp config/kalibro_processor.yml.sample config/kalibro_processor.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install
  - RAILS_ENV=local bundle exec rails s -p 8081 -d
  - cd ..
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  # Processor
  - git clone https://github.com/mezuro/kalibro_processor.git -b v0.0.1 kalibro_processor
  - cd kalibro_processor
  - psql -c "create role kalibro_processor with createdb login password 'kalibro_processor'" -U postgres
  - cp config/database.yml.postgresql_sample config/database.yml
  - cp config/repositories.yml.sample config/repositories.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle exec rake db:setup db:migrate
  - bundle install
  - bundle exec rails s -p 8082 -d
  - bundle exec bin/delayed_job start
  - cd ..
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - bundle exec rspec spec
  - bundle exec cucumber --tags ~@wip

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
